import os
import random
import time

from fastapi import FastAPI, Response
from prometheus_client import Counter, Gauge, Histogram, generate_latest, CONTENT_TYPE_LATEST

SERVICE_NAME = os.getenv("SERVICE_NAME", "app")
FAILURE_RATE = float(os.getenv("FAILURE_RATE", "0.02"))
LATENCY_SPIKE_PROBABILITY = float(os.getenv("LATENCY_SPIKE_PROBABILITY", "0.05"))

app = FastAPI(title=SERVICE_NAME)

REQUESTS = Counter(
    "app_http_requests_total",
    "Total HTTP requests",
    ["service", "method", "path", "status"],
)

REQUEST_DURATION = Histogram(
    "app_http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["service", "method", "path"],
    buckets=(0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 0.75, 1.0, 2.0, 5.0),
)

IN_FLIGHT = Gauge(
    "app_http_requests_in_flight",
    "Current in-flight requests",
    ["service"],
)

BUSINESS_EVENTS = Counter(
    "app_business_events_total",
    "Business events generated by the demo service",
    ["service", "event", "result"],
)


@app.get("/")
def root():
    start = time.perf_counter()
    IN_FLIGHT.labels(SERVICE_NAME).inc()
    status = "200"
    try:
        if random.random() < LATENCY_SPIKE_PROBABILITY:
            time.sleep(random.uniform(0.8, 1.5))
        else:
            time.sleep(random.uniform(0.01, 0.08))

        if random.random() < FAILURE_RATE:
            status = "500"
            BUSINESS_EVENTS.labels(SERVICE_NAME, "request", "failure").inc()
            return Response(
                content='{"status":"simulated failure"}',
                media_type="application/json",
                status_code=500,
            )

        BUSINESS_EVENTS.labels(SERVICE_NAME, "request", "success").inc()
        return {"service": SERVICE_NAME, "status": "ok"}
    finally:
        REQUESTS.labels(SERVICE_NAME, "GET", "/", status).inc()
        REQUEST_DURATION.labels(SERVICE_NAME, "GET", "/").observe(
            time.perf_counter() - start
        )
        IN_FLIGHT.labels(SERVICE_NAME).dec()


@app.get("/health")
def health():
    return {"status": "healthy", "service": SERVICE_NAME}


@app.get("/metrics")
def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)
