
[masters]
master1 ansible_host=172.31.18.52 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/connect.pem
 
[workers]
; worker1 ansible_host=35.173.199.41 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/connect.pem
worker2 ansible_host=54.83.134.193 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/connect.pem
worker3 ansible_host=52.91.47.11 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/connect.pem
 
[k8s_cluster:children]
masters
workers
 
[k8s_cluster:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
 