apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: apps
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: apps
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: apps
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
