apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: prom-lab/user-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
            - name: metrics
              containerPort: 8000
          env:
            - name: SERVICE_NAME
              value: "user-service"
            - name: FAILURE_RATE
              value: "0.02"
            - name: LATENCY_SPIKE_PROBABILITY
              value: "0.05"
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
