---
- name: Add Kubernetes apt repository
  ansible.builtin.import_tasks: repo.yml

- name: Install kubeadm, kubelet, kubectl
  ansible.builtin.import_tasks: install.yml

- name: Hold Kubernetes package versions
  ansible.builtin.import_tasks: hold.yml

- name: Configure crictl for containerd
  ansible.builtin.import_tasks: crictl.yml

- name: Verify Kubernetes tooling
  ansible.builtin.import_tasks: verify.yml
