apiVersion: v1
kind: Pod
metadata:
  name: user-error-traffic
  namespace: apps
spec:
  restartPolicy: Never
  containers:
    - name: traffic
      image: curlimages/curl:8.10.1
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            curl -s -o /dev/null -w "%{http_code}\n" \
              http://user-service:8000/
            sleep 0.2
          done
---
apiVersion: v1
kind: Pod
metadata:
  name: order-error-traffic
  namespace: apps
spec:
  restartPolicy: Never
  containers:
    - name: traffic
      image: curlimages/curl:8.10.1
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            curl -s -o /dev/null -w "%{http_code}\n" \
              http://order-service:8000/
            sleep 0.2
          done
---
apiVersion: v1
kind: Pod
metadata:
  name: payment-error-traffic
  namespace: apps
spec:
  restartPolicy: Never
  containers:
    - name: traffic
      image: curlimages/curl:8.10.1
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            curl -s -o /dev/null -w "%{http_code}\n" \
              http://payment-service:8000/
            sleep 0.2
          done
